var body = [
  {
    number: 0,
    name: "no bodyPart",
    layer: 1,
    source: "../../../../static/raw_sprites/spritesmith/customize/skin/skin_ea8349.png",
    coordinates: [19,32],
    category: "beard",
    size: [85,85],
  },
  {
    number: 1,
    name: "white hair bangs",
    layer: 3,
    source: "../../../../static/raw_sprites/spritesmith/customize/hair/hair_bangs_1_ghostwhite.png",
    category: "hair",
    coordinates: [17,30],
    size: [88,88],
  },
  {
    number: 2,
    name: "dark skin",
    layer: 1,
    source: "../../../../static/raw_sprites/spritesmith/customize/skin/skin_98461a.png",
    category: "skin",
    coordinates: [19,32],
    size: [85,85],
  },
  {
    number: 3,
    name: "midnight hair bangs",
    layer: 3,
    source: "../../../../static/raw_sprites/spritesmith/customize/hair/hair_bangs_1_midnight.png",
    category: "hair",
    coordinates: [17,30],
    size: [88,88],
  },
  {
    number: 4,
    name: "aurora skin",
    layer: 1,
    source: "../../../../static/raw_sprites/spritesmith/customize/skin/skin_aurora.png",
    category: "skin",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 5,
    name: "halloween hair bangs",
    layer: 3,
    source: "../../../../static/raw_sprites/spritesmith/customize/hair/hair_bangs_1_halloween.png",
    category: "hair",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 6,
    name: "green hair bangs",
    layer: 3,
    source: "../../../../static/raw_sprites/spritesmith/customize/hair/hair_bangs_1_green.png",
    category: "hair",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 7,
    name: "aurora beard",
    layer: 5,
    source: "../../../../static/raw_sprites/spritesmith/customize/beards/hair_beard_1_aurora.png",
    category: "beard",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 8,
    name: "black beard",
    layer: 5,
    source: "../../../../static/raw_sprites/spritesmith/customize/beards/hair_beard_2_black.png",
    category: "beard",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 9,
    name: "midnight beard",
    layer: 5,
    source: "../../../../static/raw_sprites/spritesmith/customize/beards/hair_beard_2_midnight.png",
    category: "beard",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 10,
    name: "frost beard",
    layer: 5,
    source: "../../../../static/raw_sprites/spritesmith/customize/beards/hair_beard_1_frost.png",
    category: "beard",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 11,
    name: "midnight beard",
    layer: 5,
    source: "../../../../static/raw_sprites/spritesmith/customize/beards/hair_beard_3_midnight.png",
    category: "beard",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 12,
    name: " candicorn hair bangs",
    layer: 3,
    source: "../../../../static/raw_sprites/spritesmith/customize/hair/hair_bangs_2_candycorn.png",
    category: "hair",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 13,
    name: "orange hair bangs",
    layer: 3,
    source: "../../../../static/raw_sprites/spritesmith/customize/hair/hair_bangs_4_porange2.png",
    category: "hair",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 14,
    name: "light skin",
    layer: 1,
    source: "../../../../static/raw_sprites/spritesmith/customize/skin/skin_ddc994.png",
    category: "skin",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 15,
    name: "winterstar skin",
    layer: 1,
    source: "../../../../static/raw_sprites/spritesmith/customize/skin/skin_winterstar.png",
    category: "skin",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 16,
    name: "dark skin",
    layer: 1,
    source: "../../../../static/raw_sprites/spritesmith/customize/skin/skin_98461a.png",
    category: "skin",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 17,
    name: "dapper skin",
    layer: 1,
    source: "../../../../static/raw_sprites/spritesmith/customize/skin/skin_dapper.png",
    category: "skin",
    coordinates: [19,32],
    size: [85,85],
  },
  {
    number: 18,
    name: "white skin",
    layer: 1,
    source: "../../../../static/raw_sprites/spritesmith/customize/skin/skin_ea8349.png",
    category: "skin",
    coordinates: [19,32],
    size: [85,85],
  },
  {
    number: 19,
    name: "broad black shirt",
    layer: 2,
    source: "../../../../static/raw_sprites/spritesmith/customize/shirts/broad_shirt_black.png",
    category: "shirt",
    coordinates: [19,32],
    size: [85,85],
  },
  {
    number: 20,
    name: "broad shirt blue",
    layer: 2,
    source: "../../../../static/raw_sprites/spritesmith/customize/shirts/broad_shirt_blue.png",
    category: "shirt",
    coordinates: [19,32],
    size: [85,85],
  },
  {
    number: 21,
    name: "broad shirt fire",
    layer: 2,
    source: "../../../../static/raw_sprites/spritesmith/customize/shirts/broad_shirt_fire.png",
    category: "shirt",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 22,
    name: "broad green shirt",
    layer: 2,
    source: "../../../../static/raw_sprites/spritesmith/customize/shirts/broad_shirt_green.png",
    category: "shirt",
    coordinates: [19,32],
    size: [85,85],
  },
  {
    number: 23,
    name: "broad shirt ocean",
    layer: 2,
    source: "../../../../static/raw_sprites/spritesmith/customize/shirts/broad_shirt_ocean.png",
    category: "shirt",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 24,
    name: "slim black shirt",
    layer: 2,
    source: "../../../../static/raw_sprites/spritesmith/customize/shirts/slim_shirt_black.png",
    category: "shirt",
    coordinates: [19,32],
    size: [85,85],
  },
  {
    number: 20,
    name: "slim blue shirt",
    layer: 2,
    source: "../../../../static/raw_sprites/spritesmith/customize/shirts/slim_shirt_blue.png",
    category: "shirt",
    coordinates: [19,32],
    size: [85,85],
  },
  {
    number: 21,
    name: "slim fire shirt",
    layer: 2,
    source: "../../../../static/raw_sprites/spritesmith/customize/shirts/slim_shirt_fire.png",
    category: "shirt",
    coordinates: [19,32],
    size: [85,85],
  },{
    number: 22,
    name: "slim green shirt",
    layer: 2,
    source: "../../../../static/raw_sprites/spritesmith/customize/shirts/slim_shirt_green.png",
    category: "shirt",
    coordinates: [19,32],
    size: [85,85],
  },
  {
    number: 23,
    name: "slim ocean shirt",
    layer: 2,
    source: "../../../../static/raw_sprites/spritesmith/customize/shirts/slim_shirt_horizon.png",
    category: "shirt",
    coordinates: [19,32],
    size: [85,85],
  },
  ],

  avatar = 
  {
    body: [18,13,11,21]
  };


//cb(avatar, body, ...) --> specify in avatar.js as well

export default {
    fetchState(cb){
        cb({
          avatar: avatar,
          body: body,
        });

    },

}

